---
apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: rhods-admins
users:
  - b64:kube:admin

# workaround to access Settings page with kubeadmin (temporal) user.
# ref: https://www.youtube.com/watch?v=aRGbumphQUE
